name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn
      - run: yarn test
      - run: yarn tsc
      - run: yarn lint
